### ISSUE TITLE
Поля формы ЮЛ

### ISSUE THREAD

**Issue by netstuff** [fastprint/fastprint#2]
Все-таки надо принять какое-то волевое решение насчет их формата.
По идее строка подойдет. Но я боюсь самостоятельно менять, вдруг все наебнется :)
Так что, друг, запланируй 5 минут своего времени на консультацию :)

**Comment by netstuff** [comment]
Жопайоптваю!
При дальнейшем заполнении формы (адрес доставки) вываливается ошибка:

invalid literal for int() with base 10: '1.23456789012e+24'
Request Method: POST
Request URL:    http://127.0.0.1:8000/profile/update/
Django Version: 1.3.1
Exception Type: ValueError
Exception Value:  
invalid literal for int() with base 10: '1.23456789012e+24'
Exception Location: /Users/netstuff/Sites/fastprintme/accounts/views.py in update, line 140
Python Executable:  /usr/bin/python
Python Version: 2.7.1
Python Path:  
['/Users/netstuff/Sites/fastprintme',
 '/Library/Python/2.7/site-packages/pip-1.0.2-py2.7.egg',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC',
 '/Library/Python/2.7/site-packages',
 '/Library/Python/2.7/site-packages/PIL']
Server time:    Чтв, 2 Фев 2012 20:20:50 +0400

Так что принимаем к сведению.
А ошибка, потому что там в поле было написано: 1.23456789012e+24

**Comment by CuriousDima** [comment]
Поля юр.лица стали теперь чарами. Для исправления этой ошибки:
1) Удали таблицы профилей и юр. адресов
2) Синхронизируйся заново с БД
fixed
